New Order: {
    id: 6950004162594,
    order_id: 5673957752866,
    kind: 'capture',
    gateway: 'bogus',
    status: 'success',
    message: 'Bogus Gateway: Forced success',
    created_at: '2025-05-23T09:15:19-04:00',
    test: true,
    authorization: null,
    location_id: null,
    user_id: null,
    parent_id: 6950004097058,
    processed_at: '2025-05-23T09:15:19-04:00',
    device_id: null,
    error_code: null,
    source_name: 'web',
    payment_details: {
      credit_card_bin: '1',
      avs_result_code: null,
      cvv_result_code: null,
      credit_card_number: '•••• •••• •••• 1',
      credit_card_company: 'Bogus',
      buyer_action_info: null,
      credit_card_name: 'groan',
      credit_card_wallet: null,
      credit_card_expiration_month: 12,
      credit_card_expiration_year: 2030,
      payment_method_name: 'bogus'
    },
    receipt: { paid_amount: '699.95' },
    amount: '699.95',
    currency: 'USD',
    payment_id: '#1009.2',
    total_unsettled_set: {
      presentment_money: { amount: '0.0', currency: 'USD' },
      shop_money: { amount: '0.0', currency: 'USD' }
    },
    manual_payment_gateway: false,
    amount_rounding: null,
    admin_graphql_api_id: 'gid://shopify/OrderTransaction/6950004162594'
  }
  New Order: {
    id: 6950023659554,
    order_id: 5673973317666,
    kind: 'authorization',
    gateway: 'bogus',
    status: 'success',
    message: 'Bogus Gateway: Forced success',
    created_at: '2025-05-23T09:26:57-04:00',
    test: true,
    authorization: '53433',
    location_id: null,
    user_id: null,
    parent_id: null,
    processed_at: '2025-05-23T09:26:57-04:00',
    device_id: null,
    error_code: null,
    source_name: 'checkout_one',
    payment_details: {
      credit_card_bin: '1',
      avs_result_code: null,
      cvv_result_code: null,
      credit_card_number: '•••• •••• •••• 1',
      credit_card_company: 'Bogus',
      buyer_action_info: null,
      credit_card_name: 'Renan',
      credit_card_wallet: null,
      credit_card_expiration_month: 12,
      credit_card_expiration_year: 2030,
      payment_method_name: 'bogus'
    },
    receipt: { authorized_amount: '1935.00' },
    amount: '1935.00',
    currency: 'USD',
    payment_id: 'r0O3cDF7gunyskFFdtc8O6K0t',
    total_unsettled_set: {
      presentment_money: { amount: '0.0', currency: 'USD' },
      shop_money: { amount: '0.0', currency: 'USD' }
    },
    manual_payment_gateway: false,
    amount_rounding: null,
    admin_graphql_api_id: 'gid://shopify/OrderTransaction/6950023659554'
  }
  New Order: {
    id: 6950023790626,
    order_id: 5673973317666,
    kind: 'capture',
    gateway: 'bogus',
    status: 'success',
    message: 'Bogus Gateway: Forced success',
    created_at: '2025-05-23T09:27:01-04:00',
    test: true,
    authorization: null,
    location_id: null,
    user_id: null,
    parent_id: 6950023659554,
    processed_at: '2025-05-23T09:27:01-04:00',
    device_id: null,
    error_code: null,
    source_name: 'web',
    payment_details: {
      credit_card_bin: '1',
      avs_result_code: null,
      cvv_result_code: null,
      credit_card_number: '•••• •••• •••• 1',
      credit_card_company: 'Bogus',
      buyer_action_info: null,
      credit_card_name: 'Renan',
      credit_card_wallet: null,
      credit_card_expiration_month: 12,
      credit_card_expiration_year: 2030,
      payment_method_name: 'bogus'
    },
    receipt: { paid_amount: '1935.00' },
    amount: '1935.00',
    currency: 'USD',
    payment_id: '#1010.2',
    total_unsettled_set: {
      presentment_money: { amount: '0.0', currency: 'USD' },
      shop_money: { amount: '0.0', currency: 'USD' }
    },
    manual_payment_gateway: false,
    amount_rounding: null,
    admin_graphql_api_id: 'gid://shopify/OrderTransaction/6950023790626'
  }
  